### ISSUE TITLE
Use of new access token based authentication in this SDK

### ISSUE THREAD

**Issue by bikram-bikram** [walmartlabs/partnerapi_sdk_dotnet#12]
I recently noticed on the API Keys page in developer portal that Walmart is going to deprecate the "signature method" and recommends developers to start using the "new token based authentication".

Is there a roadmap for this dotnet sdk to use the new token based authentication anytime soon?

![image](https://user-images.githubusercontent.com/34821479/46385908-82fadd80-c68c-11e8-85df-4aa4bf8ca163.png)

**Comment by roman-shuhov** [comment]
Thank you for pointing this! We don't have a timeline for this feature right now, but let's keep this issue open to track progress. We will post an update as soon as roadmap will be  confirmed.

**Comment by dkershner6** [comment]
Just as a note, the deprecation of the method is on August 28th, about 2 months away, where this library will no longer function.

**Comment by weirdian2k3** [comment]
@dkershner6 Hi Derek, I've used this patch on my local fork to get it working: https://github.com/walmartlabs/partnerapi_sdk_dotnet/commit/71f35acc6204298600d3ce5c170c51a8e323c5a6

It's been working successfully

**Comment by dkershner6** [comment]
That indeed looks promising, thanks for the link @weirdian2k3

**Comment by aminecraftplayerx** [comment]
Can you tell me what the accessToken parameter is supposed to be set to?

**Comment by aminecraftplayerx** [comment]
Figured it out, got it all working...
