### ISSUE TITLE
Charges and OrderStatuses

### ISSUE THREAD

**Issue by jmawebtech** [walmartlabs/partnerapi_sdk_dotnet#2]
Hi,

In your code, the software fails to see the charges or the order statuses list in the order object. In the attached screenshot, the charge should have a value.

![data2](https://user-images.githubusercontent.com/1679993/40945431-c4bf0fbc-6826-11e8-9206-e06ae852748e.jpg)

![data3](https://user-images.githubusercontent.com/1679993/40945463-f1859188-6826-11e8-85a1-197c010f42ef.jpg)

[data.txt](https://github.com/walmartlabs/partnerapi_sdk_dotnet/files/2070199/data.txt)

**Comment by roman-shuhov** [comment]
@jmawebtech can you check code from the branch bugfix/2? should fix this issue.

**Comment by jmawebtech** [comment]
Works great, thanks!
