### ISSUE TITLE
Order not found Bad request fromDate or toDate is missing

### ISSUE THREAD

**Issue by jmawebtech** [walmartlabs/partnerapi_sdk_dotnet#3]
Hi,

I am trying to pull a list of shipped orders. Why does this request fail?

GET https://marketplace.walmartapis.com/v3/orders?status=Shipped&fromExpectedShipDate=2018-06-01&toExpectedShipDate=2018-06-05&limit=20 HTTP/1.1

Order not found Bad request fromDate or toDate is missing

**Comment by roman-shuhov** [comment]
I think you also need to pass createdStartDate, this field is required according to documentation - https://developer.walmart.com/#/apicenter/marketPlace/latest#getAllOrders

**Comment by roman-shuhov** [comment]
feel free to reopen if you have more questions about this issue.
