### ISSUE TITLE
Can't create or Update an item

### ISSUE THREAD

**Issue by osya** [walmartlabs/partnerapi_sdk_dotnet#7]
I tried to use Sample app. I tried to check creating and updating items using standard template `itemFeed.xml`. The following error appears: `The data isn't formatted properly. Please resubmit the data file in the correct format`. Please advise

**Comment by roman-shuhov** [comment]
looking into it

**Comment by roman-shuhov** [comment]
I'll update itemFeed in a separate issue you created. This error message is indeed misleading, but right now that all we are getting from the API. I recommend to create a topic at https://developer.walmart.com/forums/index.php/forums to get help with any validation issues you have.
